import io
from typing import Any

from reportlab.lib import colors  # type: ignore[import-untyped]
from reportlab.lib.pagesizes import letter  # type: ignore[import-untyped]
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet  # type: ignore[import-untyped]
from reportlab.pdfgen import canvas  # type: ignore[import-untyped]
from reportlab.platypus import (  # type: ignore[import-untyped]
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.report import AnalysisReport


class NumberedCanvas(canvas.Canvas):  # type: ignore[misc]
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int) -> None:
        self.saveState()

        # Don't draw headers/footers on the cover page (Page 1)
        if self._pageNumber > 1:
            # Running Header
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(colors.HexColor("#060814"))
            self.drawString(54, 750, "CODEMEDIC AI  |  Code Diagnostics & Optimization Report")
            self.setStrokeColor(colors.HexColor("#1e293b"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

            # Running Footer
            self.line(54, 60, 558, 60)
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor("#64748b"))
            self.drawString(54, 45, "Generated by CodeMedic AI  •  Fix. Explain. Optimize.")
            self.drawRightString(558, 45, f"Page {self._pageNumber} of {page_count}")

        self.restoreState()


def generate_report_pdf(report: AnalysisReport) -> io.BytesIO:
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72,
    )

    styles = getSampleStyleSheet()

    primary_color = colors.HexColor("#0f172a")  # Slate-900
    accent_color = colors.HexColor("#06b6d4")  # Cyan-500
    text_color = colors.HexColor("#334155")  # Slate-700

    title_style = ParagraphStyle(
        "CoverTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=34,
        textColor=primary_color,
        alignment=0,
        spaceAfter=15,
    )

    subtitle_style = ParagraphStyle(
        "CoverSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=30,
    )

    h1_style = ParagraphStyle(
        "Heading1Custom",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=primary_color,
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True,
    )

    h2_style = ParagraphStyle(
        "Heading2Custom",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=primary_color,
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        "BodyCustom",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=text_color,
        spaceAfter=8,
    )

    code_style = ParagraphStyle(
        "CodeCustom",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#0f172a"),
        backColor=colors.HexColor("#f8fafc"),
        borderColor=colors.HexColor("#e2e8f0"),
        borderWidth=0.5,
        borderPadding=6,
        spaceAfter=10,
    )

    story = []

    # ------------------ COVER PAGE ------------------
    story.append(Spacer(1, 80))
    story.append(Paragraph("CodeMedic AI", title_style))
    story.append(Paragraph("Fix. Explain. Optimize. Powered by AI Engine.", subtitle_style))

    story.append(
        Table(
            [[""]],
            colWidths=[504],
            rowHeights=[2],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), accent_color),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                ]
            ),
        )
    )
    story.append(Spacer(1, 25))

    created_str = report.created_at.strftime("%B %d, %Y %I:%M %p")
    metadata_data = [
        [Paragraph("<b>File Name:</b>", body_style), Paragraph(report.file_name, body_style)],
        [
            Paragraph("<b>Language:</b>", body_style),
            Paragraph(report.language.capitalize(), body_style),
        ],
        [
            Paragraph("<b>Analysis Type:</b>", body_style),
            Paragraph(report.analysis_type, body_style),
        ],
        [Paragraph("<b>Date Generated:</b>", body_style), Paragraph(created_str, body_style)],
        [
            Paragraph("<b>Confidence Score:</b>", body_style),
            Paragraph(f"{report.confidence}%", body_style),
        ],
    ]
    metadata_table = Table(metadata_data, colWidths=[130, 374])
    metadata_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    story.append(metadata_table)

    story.append(Spacer(1, 30))

    score_data = [
        ["Quality Score", "Bug Count", "Security Score"],
        [f"{report.code_quality_score}/100", str(report.bug_count), f"{report.security_score}/100"],
    ]
    score_table = Table(score_data, colWidths=[168, 168, 168])
    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("TEXTCOLOR", (0, 0), (-1, 0), primary_color),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 10),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f8fafc")),
                ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 1), (-1, 1), 18),
                (
                    "TEXTCOLOR",
                    (0, 1),
                    (0, 1),
                    (
                        colors.HexColor("#0ea5e9")
                        if report.code_quality_score >= 80
                        else colors.HexColor("#f59e0b")
                    ),
                ),
                (
                    "TEXTCOLOR",
                    (1, 1),
                    (1, 1),
                    (
                        colors.HexColor("#ef4444")
                        if report.bug_count > 0
                        else colors.HexColor("#10b981")
                    ),
                ),
                (
                    "TEXTCOLOR",
                    (2, 1),
                    (2, 1),
                    (
                        colors.HexColor("#10b981")
                        if report.security_score >= 90
                        else colors.HexColor("#ef4444")
                    ),
                ),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )
    story.append(score_table)
    story.append(PageBreak())

    # ------------------ EXECUTIVE SUMMARY ------------------
    story.append(Paragraph("Executive Summary", h1_style))
    story.append(Paragraph(report.summary or "CodeMedic AI diagnostic scan completed.", body_style))
    story.append(Spacer(1, 15))

    story.append(Paragraph("Complexity Estimates", h2_style))
    comp_time = (report.complexity or {}).get("time", "O(1)")
    comp_space = (report.complexity or {}).get("space", "O(1)")
    comp_details = (report.complexity or {}).get("explanation", "Asymptotic analysis completed.")
    complexity_text = (
        f"<b>Time Complexity:</b> {comp_time}<br/>"
        f"<b>Space Complexity:</b> {comp_space}<br/><br/>"
        f"{comp_details}"
    )
    story.append(Paragraph(complexity_text, body_style))
    story.append(Spacer(1, 15))

    # ------------------ DETECTED BUGS ------------------
    story.append(Paragraph("Detected Bugs & Code Issues", h1_style))
    if not report.issues:
        story.append(
            Paragraph("No code issues or bugs were detected. Implementation is clean.", body_style)
        )
    else:
        for idx, issue in enumerate(report.issues, 1):
            if isinstance(issue, dict):
                title = issue.get("title", f"Issue #{idx}")
                desc = issue.get("description", "")
                sev = str(issue.get("severity", "low")).upper()
                line = issue.get("line") or issue.get("line_number")
                fix = issue.get("fix")
            else:
                title, desc, sev, line, fix = f"Issue #{idx}", str(issue), "LOW", None, None

            line_str = f" (Line {line})" if line else ""
            story.append(
                Paragraph(
                    f"<b>{idx}. {title}</b> — <font color='red'><b>{sev}</b></font>{line_str}",
                    h2_style,
                )
            )
            story.append(Paragraph(desc, body_style))
            if fix:
                story.append(Paragraph(f"<b>Fix Recommendation:</b> {fix}", body_style))
    story.append(Spacer(1, 15))

    # ------------------ SECURITY ANALYSIS ------------------
    story.append(Paragraph("Security & Credentials Check", h1_style))
    if not report.security:
        story.append(
            Paragraph(
                "No exposure of secrets, credentials, or common OWASP vulnerabilities detected.",
                body_style,
            )
        )
    else:
        for idx, sec in enumerate(report.security, 1):
            if isinstance(sec, dict):
                finding = sec.get("finding") or sec.get("title") or f"Finding #{idx}"
                sev = str(sec.get("severity", "low")).upper()
                fix = sec.get("fix") or sec.get("description")
            else:
                finding, sev, fix = f"Finding #{idx}", "LOW", str(sec)

            story.append(
                Paragraph(
                    f"<b>{idx}. {finding}</b> — <font color='orange'><b>{sev}</b></font>", h2_style
                )
            )
            if fix:
                story.append(Paragraph(f"<b>Remediation:</b> {fix}", body_style))
    story.append(Spacer(1, 15))

    # ------------------ PERFORMANCE ANALYSIS ------------------
    story.append(Paragraph("Performance Recommendations", h1_style))
    if not report.performance:
        story.append(
            Paragraph(
                "Code is optimized for fast processing speeds and minimal resource consumption.",
                body_style,
            )
        )
    else:
        for idx, perf in enumerate(report.performance, 1):
            if isinstance(perf, dict):
                p_issue = perf.get("issue") or perf.get("title") or f"Performance Item #{idx}"
                impact = perf.get("impact", "Low")
                fix = perf.get("fix") or perf.get("description")
            else:
                p_issue, impact, fix = f"Performance Item #{idx}", "Low", str(perf)

            story.append(Paragraph(f"<b>{idx}. {p_issue}</b> — Impact: <b>{impact}</b>", h2_style))
            if fix:
                story.append(Paragraph(f"<b>Optimization Suggestion:</b> {fix}", body_style))

    story.append(PageBreak())

    # ------------------ OPTIMIZED SOURCE CODE ------------------
    story.append(Paragraph("Optimized Source Code", h1_style))
    story.append(
        Paragraph(
            "This is the optimized and secure code snippet to replace the original source code.",
            body_style,
        )
    )
    opt_code = report.optimized_code or "// No optimized code provided"
    story.append(Preformatted(opt_code, code_style, maxLineLength=80))
    story.append(Spacer(1, 15))

    # ------------------ SUGGESTED UNIT TESTS ------------------
    story.append(Paragraph("Suggested Test Cases", h1_style))
    story.append(
        Paragraph(
            "Below is a template of unit test cases matching key edge cases.",
            body_style,
        )
    )
    if not report.tests:
        story.append(Paragraph("No automated test cases suggested.", body_style))
    else:
        tests_text = "\n\n".join(report.tests)
        story.append(Preformatted(tests_text, code_style, maxLineLength=80))

    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer
