import io
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.report import AnalysisReport


class NumberedCanvas(canvas.Canvas):  # type: ignore[misc]
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict[str, Any]] = []

    def showPage(self) -> None:
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int) -> None:
        self.saveState()

        # Don't draw headers/footers on cover page
        if self._pageNumber > 1:
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(colors.HexColor("#060814"))
            self.drawString(54, 750, "CODEMEDIC AI  |  Executive Engineering & Security Report")
            self.setStrokeColor(colors.HexColor("#1e293b"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

            self.line(54, 60, 558, 60)
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor("#64748b"))
            self.drawString(
                54,
                45,
                "Generated by CodeMedic AI  •  Fix. Explain. Optimize. Powered by AI Engine.",
            )
            self.drawRightString(558, 45, f"Page {self._pageNumber} of {page_count}")

        self.restoreState()


def generate_report_pdf(report: AnalysisReport) -> io.BytesIO:
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72,
    )

    styles = getSampleStyleSheet()

    primary_color = colors.HexColor("#0f172a")  # Slate-900
    accent_color = colors.HexColor("#06b6d4")  # Cyan-500
    text_color = colors.HexColor("#334155")  # Slate-700

    title_style = ParagraphStyle(
        "CoverTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=26,
        leading=32,
        textColor=primary_color,
        alignment=0,
        spaceAfter=12,
    )

    subtitle_style = ParagraphStyle(
        "CoverSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=25,
    )

    h1_style = ParagraphStyle(
        "Heading1Custom",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        textColor=primary_color,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True,
    )

    h2_style = ParagraphStyle(
        "Heading2Custom",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=primary_color,
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True,
    )

    body_style = ParagraphStyle(
        "BodyCustom",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13.5,
        textColor=text_color,
        spaceAfter=6,
    )

    code_style = ParagraphStyle(
        "CodeCustom",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=7.5,
        leading=9.5,
        textColor=colors.HexColor("#0f172a"),
        backColor=colors.HexColor("#f8fafc"),
        borderColor=colors.HexColor("#cbd5e1"),
        borderWidth=0.5,
        borderPadding=6,
        spaceAfter=10,
    )

    story = []

    # ------------------ COVER PAGE ------------------
    story.append(Spacer(1, 60))
    story.append(Paragraph("CodeMedic AI Audit Report", title_style))
    story.append(
        Paragraph("Fix. Explain. Optimize. Powered by AI Developer Engine.", subtitle_style)
    )

    story.append(
        Table(
            [[""]],
            colWidths=[504],
            rowHeights=[2],
            style=TableStyle([("BACKGROUND", (0, 0), (-1, -1), accent_color)]),
        )
    )
    story.append(Spacer(1, 20))

    created_str = report.created_at.strftime("%B %d, %Y %I:%M %p")
    metadata_data = [
        [
            Paragraph("<b>Target Target File:</b>", body_style),
            Paragraph(report.file_name, body_style),
        ],
        [
            Paragraph("<b>Language Environment:</b>", body_style),
            Paragraph(report.language.capitalize(), body_style),
        ],
        [
            Paragraph("<b>Diagnostic Preset:</b>", body_style),
            Paragraph(report.analysis_type, body_style),
        ],
        [Paragraph("<b>Scan Timestamp:</b>", body_style), Paragraph(created_str, body_style)],
        [
            Paragraph("<b>AI Confidence Rating:</b>", body_style),
            Paragraph(f"{report.confidence}%", body_style),
        ],
    ]
    metadata_table = Table(metadata_data, colWidths=[140, 364])
    metadata_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    story.append(metadata_table)

    story.append(Spacer(1, 25))

    # Dynamic Scores Matrix
    score_data = [
        ["Overall Health", "Security Score", "Performance", "Total Bugs"],
        [
            f"{report.code_quality_score}/100",
            f"{report.security_score}/100",
            f"{(report.complexity or {}).get('time', 'O(N)')}",
            str(report.bug_count),
        ],
    ]
    score_table = Table(score_data, colWidths=[126, 126, 126, 126])
    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("TEXTCOLOR", (0, 0), (-1, 0), primary_color),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f8fafc")),
                ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 1), (-1, 1), 16),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(score_table)
    story.append(PageBreak())

    # ------------------ EXECUTIVE SUMMARY & AI EXPLANATION ------------------
    story.append(Paragraph("1. Executive Summary", h1_style))
    story.append(Paragraph(report.summary or "CodeMedic AI diagnostic scan completed.", body_style))
    story.append(Spacer(1, 10))

    if report.code_explanation:
        story.append(Paragraph("Detailed AI Code Explanation", h2_style))
        story.append(Paragraph(report.code_explanation.replace("\n", "<br/>"), body_style))
        story.append(Spacer(1, 10))

    # ------------------ DETECTED BUGS ------------------
    story.append(Paragraph("2. Detected Code Flaws & Bugs", h1_style))
    if not report.issues:
        story.append(Paragraph("No code issues or bugs were detected.", body_style))
    else:
        for idx, issue in enumerate(report.issues, 1):
            title = issue.get("title", f"Issue #{idx}")
            desc = issue.get("description", "")
            sev = str(issue.get("severity", "low")).upper()
            line = issue.get("line") or issue.get("line_number")
            why = issue.get("why_it_happens")
            impact = issue.get("impact")
            fix = issue.get("fix")
            fix_code = issue.get("fix_code")

            line_str = f" (Line {line})" if line else ""
            story.append(
                Paragraph(
                    f"<b>{idx}. {title}</b> — <font color='red'><b>{sev}</b></font>{line_str}",
                    h2_style,
                )
            )
            story.append(Paragraph(desc, body_style))
            if why:
                story.append(Paragraph(f"<b>Root Cause:</b> {why}", body_style))
            if impact:
                story.append(Paragraph(f"<b>Impact:</b> {impact}", body_style))
            if fix:
                story.append(Paragraph(f"<b>Fix:</b> {fix}", body_style))
            if fix_code:
                story.append(Preformatted(fix_code, code_style, maxLineLength=75))

    story.append(Spacer(1, 10))

    # ------------------ SECURITY ANALYSIS ------------------
    story.append(Paragraph("3. Security & OWASP Audit", h1_style))
    if not report.security:
        story.append(
            Paragraph(
                "No exposure of secrets or OWASP Top 10 vulnerabilities detected.", body_style
            )
        )
    else:
        for idx, sec in enumerate(report.security, 1):
            finding = sec.get("finding") or sec.get("title") or f"Finding #{idx}"
            sev = str(sec.get("severity", "low")).upper()
            owasp = sec.get("owasp_category", "OWASP General")
            remediation = sec.get("remediation") or sec.get("fix")

            story.append(
                Paragraph(
                    f"<b>{idx}. {finding}</b> — <font color='orange'><b>[{owasp}] {sev}</b></font>",
                    h2_style,
                )
            )
            if remediation:
                story.append(Paragraph(f"<b>Remediation:</b> {remediation}", body_style))

    story.append(Spacer(1, 10))

    # ------------------ SENIOR CODE REVIEW ------------------
    if report.code_review:
        story.append(Paragraph("4. Senior Code Review & SOLID Architecture", h1_style))
        for idx, cr in enumerate(report.code_review, 1):
            cat = cr.get("category", f"Category #{idx}")
            status = str(cr.get("status", "pass")).upper()
            sug = cr.get("suggestion", "")
            story.append(Paragraph(f"<b>{idx}. {cat}</b> — Status: <b>{status}</b>", h2_style))
            story.append(Paragraph(sug, body_style))

    story.append(PageBreak())

    # ------------------ OPTIMIZED SOURCE CODE ------------------
    story.append(Paragraph("5. Optimized Source Code & Refactoring", h1_style))
    if report.why_better:
        story.append(Paragraph("<b>Why this version is better:</b>", h2_style))
        story.append(Paragraph(report.why_better.replace("\n", "<br/>"), body_style))
        story.append(Spacer(1, 8))

    opt_code = report.optimized_code or "// No optimized code provided"
    story.append(Preformatted(opt_code, code_style, maxLineLength=75))
    story.append(Spacer(1, 10))

    # ------------------ SUGGESTED UNIT TESTS ------------------
    story.append(Paragraph("6. Production Unit Test Suite", h1_style))
    if not report.tests:
        story.append(Paragraph("No automated test cases suggested.", body_style))
    else:
        tests_text = "\n\n".join(report.tests)
        story.append(Preformatted(tests_text, code_style, maxLineLength=75))

    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer
