"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { CheckCircle2, LoaderCircle } from "lucide-react";
import { useAuth } from "./auth-provider";
import { AuthShell, FieldError, inputClass } from "./auth-shell";
import { authService } from "@/services/auth";

const password = z.string().min(12, "Use at least 12 characters.").max(128);
const email = z.string().email("Enter a valid email address.");
const loginSchema = z.object({ email, password: z.string().min(1, "Password is required."), rememberMe: z.boolean() });
const registerSchema = z.object({ fullName: z.string().min(2, "Enter your full name."), email, password, confirmPassword: z.string(), terms: z.literal(true, { errorMap: () => ({ message: "Please accept the terms." }) }) }).refine((value) => value.password === value.confirmPassword, { path: ["confirmPassword"], message: "Passwords do not match." });

function Submit({ pending, children }: Readonly<{ pending: boolean; children: React.ReactNode }>) { return <button disabled={pending} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-4 py-3 font-semibold text-white transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60">{pending && <LoaderCircle className="size-4 animate-spin" />}{children}</button>; }

export function LoginForm() { const router = useRouter(); const { signIn } = useAuth(); const [error, setError] = useState(""); const form = useForm<z.infer<typeof loginSchema>>({ resolver: zodResolver(loginSchema), defaultValues: { rememberMe: true } }); const submit = form.handleSubmit(async (data) => { setError(""); try { await signIn(data.email, data.password, data.rememberMe); router.replace("/dashboard"); } catch (issue) { setError(issue instanceof Error ? issue.message : "Unable to sign in."); } }); return <AuthShell title="Welcome back" description="Sign in to continue your code health workflow."><form onSubmit={submit} noValidate className="mt-7"><Label label="Email"><input type="email" autoComplete="email" className={inputClass} {...form.register("email")} /></Label><FieldError message={form.formState.errors.email?.message} /><Label label="Password"><input type="password" autoComplete="current-password" className={inputClass} {...form.register("password")} /></Label><FieldError message={form.formState.errors.password?.message} /><div className="mt-4 flex items-center justify-between"><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" className="accent-cyan-400" {...form.register("rememberMe")} />Remember me</label><Link href="/forgot-password" className="text-xs text-cyan-300 hover:text-cyan-200">Forgot password?</Link></div>{error && <p role="alert" className="mt-4 text-sm text-rose-300">{error}</p>}<Submit pending={form.formState.isSubmitting}>Login</Submit><button type="button" className="mt-3 w-full rounded-xl border border-slate-700 px-4 py-3 text-sm font-medium text-slate-300 hover:bg-slate-800">Continue with Google <span className="text-slate-500">(coming soon)</span></button><p className="mt-6 text-center text-sm text-slate-400">New to CodeMedic? <Link href="/register" className="text-cyan-300 hover:text-cyan-200">Create an account</Link></p></form></AuthShell>; }

export function RegisterForm() { const router = useRouter(); const { signUp } = useAuth(); const [error, setError] = useState(""); const form = useForm<z.infer<typeof registerSchema>>({ resolver: zodResolver(registerSchema) }); const value = form.watch("password") ?? ""; const strength = value.length >= 12 ? "Strong" : value.length >= 8 ? "Fair" : "Weak"; const submit = form.handleSubmit(async (data) => { setError(""); try { await signUp(data.fullName, data.email, data.password); router.replace("/dashboard"); } catch (issue) { setError(issue instanceof Error ? issue.message : "Unable to register."); } }); return <AuthShell title="Create your workspace" description="Start making every review more useful."><form onSubmit={submit} noValidate className="mt-7"><Label label="Full name"><input autoComplete="name" className={inputClass} {...form.register("fullName")} /></Label><FieldError message={form.formState.errors.fullName?.message} /><Label label="Email"><input type="email" autoComplete="email" className={inputClass} {...form.register("email")} /></Label><FieldError message={form.formState.errors.email?.message} /><Label label="Password"><input type="password" autoComplete="new-password" className={inputClass} {...form.register("password")} /></Label><div className="mt-2 flex items-center gap-2 text-xs text-slate-500"><span className={`h-1.5 flex-1 rounded-full ${strength === "Weak" ? "bg-rose-400" : strength === "Fair" ? "bg-amber-400" : "bg-emerald-400"}`} />Password strength: {strength}</div><FieldError message={form.formState.errors.password?.message} /><Label label="Confirm password"><input type="password" autoComplete="new-password" className={inputClass} {...form.register("confirmPassword")} /></Label><FieldError message={form.formState.errors.confirmPassword?.message} /><label className="mt-5 flex gap-2 text-xs leading-5 text-slate-400"><input type="checkbox" className="mt-1 accent-cyan-400" {...form.register("terms")} />I agree to the terms and privacy policy.</label><FieldError message={form.formState.errors.terms?.message} />{error && <p role="alert" className="mt-4 text-sm text-rose-300">{error}</p>}<Submit pending={form.formState.isSubmitting}>Create account</Submit><p className="mt-6 text-center text-sm text-slate-400">Already have an account? <Link href="/login" className="text-cyan-300 hover:text-cyan-200">Login</Link></p></form></AuthShell>; }

export function ForgotPasswordForm() { const [sent, setSent] = useState(false); const form = useForm<{ email: string }>({ resolver: zodResolver(z.object({ email })) }); const submit = form.handleSubmit(async ({ email: address }) => { await authService.forgotPassword(address); setSent(true); }); return <AuthShell title="Reset your password" description="Enter your account email and we’ll send a reset link.">{sent ? <div className="mt-7 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-4 text-sm text-emerald-100"><CheckCircle2 className="mb-2 size-5" />If an account exists, a reset link is on its way.</div> : <form onSubmit={submit} className="mt-7"><Label label="Email"><input type="email" className={inputClass} {...form.register("email")} /></Label><FieldError message={form.formState.errors.email?.message} /><Submit pending={form.formState.isSubmitting}>Send reset link</Submit></form>}<p className="mt-6 text-center text-sm text-slate-400"><Link href="/login" className="text-cyan-300">Back to login</Link></p></AuthShell>; }

function Label({ label, children }: Readonly<{ label: string; children: React.ReactNode }>) { return <label className="mt-4 block text-sm font-medium text-slate-200">{label}{children}</label>; }
